apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uat-ims
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/infra-gitops.git
    targetRevision: main
    path: environments/uat/ims
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true        # UAT: enforce đúng trạng thái Git
    syncOptions:
      - CreateNamespace=true
