apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-tc-ims-be
  namespace: argocd
spec:
  project: tc-hrm-project
  source:
    repoURL: https://github.com/YOUR_ORG/infra-gitops.git
    targetRevision: main
    path: manifests/dev/tc-ims-be
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
