---
# Thay thế configs/secrets/postgres-dev-secret.yaml (manual Secret)
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-dev-secret
  namespace: data
spec:
  vaultAuthRef: data-auth
  type: kv-v2
  mount: secret
  path: data/postgres-dev
  destination:
    name: postgres-dev-secret
    create: true
  refreshAfter: 60s
---
# Thay thế configs/secrets/postgres-uat-secret.yaml (manual Secret)
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-uat-secret
  namespace: data
spec:
  vaultAuthRef: data-auth
  type: kv-v2
  mount: secret
  path: data/postgres-uat
  destination:
    name: postgres-uat-secret
    create: true
  refreshAfter: 60s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-dev-secret
  namespace: data
spec:
  vaultAuthRef: data-auth
  type: kv-v2
  mount: secret
  path: data/redis-dev
  destination:
    name: redis-dev-secret
    create: true
  refreshAfter: 60s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-uat-secret
  namespace: data
spec:
  vaultAuthRef: data-auth
  type: kv-v2
  mount: secret
  path: data/redis-uat
  destination:
    name: redis-uat-secret
    create: true
  refreshAfter: 60s
