---
# Thay thế configs/secrets/app-uat-secret.yaml (manual Secret)
# Dùng chung cho 5 apps trong namespace uat
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-uat-secret
  namespace: uat
spec:
  vaultAuthRef: uat-auth
  type: kv-v2
  mount: secret
  path: uat/app
  destination:
    name: app-uat-secret
    create: true
  refreshAfter: 60s
