---
# Thay thế configs/secrets/app-dev-secret.yaml (manual Secret)
# Dùng chung cho 5 apps trong namespace dev
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-dev-secret
  namespace: dev
spec:
  vaultAuthRef: dev-auth
  type: kv-v2
  mount: secret
  path: dev/app
  destination:
    name: app-dev-secret
    create: true
  refreshAfter: 60s
