---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: elasticsearch-password
  namespace: monitoring
spec:
  vaultAuthRef: monitoring-auth
  type: kv-v2
  mount: secret
  path: monitoring/elasticsearch
  destination:
    name: elasticsearch-password
    create: true
  refreshAfter: 60s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: elasticsearch-password
  namespace: dev
spec:
  vaultAuthRef: dev-auth
  type: kv-v2
  mount: secret
  path: monitoring/elasticsearch
  destination:
    name: elasticsearch-password
    create: true
  refreshAfter: 60s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: elasticsearch-password
  namespace: uat
spec:
  vaultAuthRef: uat-auth
  type: kv-v2
  mount: secret
  path: monitoring/elasticsearch
  destination:
    name: elasticsearch-password
    create: true
  refreshAfter: 60s
