apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tc-hrm-project
  namespace: argocd
spec:
  description: TC Platform project
  sourceRepos:
    - https://github.com/YOUR_ORG/infra-gitops.git
z
