apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tc-cms-be-category
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: dev-vpn-only@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dev-tc-cms-be-category.company.com
      secretName: dev-tc-cms-be-category-tls
  rules:
    - host: dev-tc-cms-be-category.company.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tc-cms-be-category
                port:
                  number: 80
